Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 512
      Handler: com.thinksy.lambda.FruitDetectorLambda
      CodeUri: /Users/amin/Developments/appsrc/practise/aws-qurakus/aws-lambda-handler
      Runtime: java11